name: Actualización Diaria Renfe

on:
  schedule:
    # Se ejecuta a las 08:00 UTC (9:00 AM hora peninsular en invierno)
    - cron: '0 8 * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente para probar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install requests pandas

      - name: Ejecutar script de conversión
        run: python main.py

      - name: Guardar cambios en el repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data_csv/*.csv
          git commit -m "Actualización automática: $(date)" || exit 0
          git push